version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    networks:
      db-app:
        aliases:
          - db
  test:
    depends_on:
      - dynamodb-local
    build: .
    container_name: app-node
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    networks:
       db-app:
       default:
networks:
  db-app:
  default:
      driver: bridge
